modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/5w14/auth-logic/issues"
license = "MIT"

[[mods]]
modId = "authlogic"
version = "${version}"
displayName = "AuthLogic"
authors = "5w14"
description = '''
Simple and effective authentication solution for modded servers.
'''
logoFile = "icon.png"

[[mixins]]
config = "authlogic.mixins.json"

[[dependencies.authlogic]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.authlogic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.authlogic]]
modId = "architectury"
mandatory = true
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"
